### ISSUE TITLE
lcp-ng not copy to vpp from kernel

### ISSUE THREAD

**Issue by ahmdzaki18** [pimvanpelt/lcpng#11]
Hi,

i using lcp-ng from vpp 22.10 until now on stable 23.10 with no issue. Because if i using original linux-cp, i got subif goes up and down if set different mtu with parent interface (i dont know its fixed now or not).
until this happen. some routes not installed into vpp ip fib only on this new machine, i dont know why.

sometimes like this,
prefix available on kernel but not available on vpp fib,
![WhatsApp Image 2024-02-20 at 05 34 02_b465ff31](https://github.com/pimvanpelt/lcpng/assets/123150516/76ad80ce-5789-4f2f-beb1-bbf0f83a7684)

prefix available on frr also,
![WhatsApp Image 2024-02-20 at 05 34 33_aebb0fdb](https://github.com/pimvanpelt/lcpng/assets/123150516/0e0dbd17-395b-4ab3-a267-f4cde0de424d)

to solve, i need disable the interface or peer to move on another next-hop, then bring it up again (another example prefix),
![WhatsApp Image 2024-02-20 at 03 52 01_59c62050](https://github.com/pimvanpelt/lcpng/assets/123150516/c55f8370-7606-4bb8-a956-58f32b5704d8)

My configuration:
3 IXP Equinix Singapore, BBIX Singapore, SGIX with some bilateral inside it.
2 Route Reflector full routes
iBGP with OSPF all p2p network

My Node:
Debian Bullseye latest
5.10.0-28-amd64
vpp v23.10.0-22~g6b287b530 built by root on cbr-sgx-rtr
FRRouting 9.1
Intel(R) Xeon(R) CPU E3-1280 v5 @ 3.70GHz (performance governor)
32GB ECC DDR4 (8GB x 4)
Intel XL710 QDA1 latest firmware

NB: i tried original linux-cp plugin and vpp fib works normal with parent and subif same mtu (1500), but very weird some website like keep loading forever (like not enough mtu).

is kernel too fast so vpp cannot keep up to install fib? but original linux-cp works normal. And i tried also using lcpng and enable peer one by one without issue. or poll-sleep-usec take effect? now poll-sleep-usec 1000
what command or output i need to share for further analysis?

**Comment by pimvanpelt** [comment]
The warning in the README clearly spells out that there is no support in this github repo.
You can reach out to vpp-dev@lists.fd.io for general questions, or sales@ipng.ch for paid support.
