### ISSUE TITLE
Compilation issues[1]

### ISSUE THREAD

**Issue by yw1573** [pimvanpelt/lcpng#4]
error1:plugins/lcpng/lcpng_netlink.c:90:15: error: implicit declaration of function ‘rtnl_route_nh_get_via’; did you mean ‘rtnl_route_nh_get_flags’? [-Werror=implicit-function-declaration]
   90 |      if ((a = rtnl_route_nh_get_via (nh)))
      |               ^~~~~~~~~~~~~~~~~~~~~
      |               rtnl_route_nh_get_flags
error2:/plugins/lcpng/lcpng_netlink.c:95:15: error: implicit declaration of function ‘rtnl_route_nh_get_newdst’; did you mean ‘rtnl_route_nh_get_weight’? [-Werror=implicit-function-declaration]
   95 |      if ((a = rtnl_route_nh_get_newdst (nh)))
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
      |               rtnl_route_nh_get_weight

Gangster：
     Compile error at vpp21.06，linux kernel version at 4.19.145

I don't know if I can answer it

**Comment by pimvanpelt** [comment]
As noted in the README, there is (and will be) no support on this repo. 

Please contact vpp-dev@lists.fd.io for support on VPP. Note that the only target to reasonably compile VPP on is Ubuntu LTS 20.04.

**Comment by tmuehlhoff** [comment]
@yw1573 did you get that resolved ?

**Comment by pimvanpelt** [comment]
Although there is no support on this repo, I will point out that `lcpng` only works with current VPP, which is at version 22.02. It requires an uptodate libnl-3 library, version 3.7.0 or above.

**Comment by tmuehlhoff** [comment]
Thank you, understood!
